version: 1.0.{build}
clone_depth: 5
force_https_clone: true
os: Visual Studio 2015
environment:
  XAMARIN_COOKIE: 3942059bcda946efb162fdc8c9d284c6
  REPO_CLONE_ATTEMPTS: 5
  REPO_CLONE_TIMEOUT: 180
  REPO_CLONE_PROTOCOL: https
  buildconfig: Release
  matrix:
  - test_type: Integration.Testing
    test_assemblies: UnitTestProject1\bin\$env:buildconfig\UnitTestProject1.dll
    test_category: Integration
    test_settings: AppVeyorTest1.testsettings
matrix:
    fast_finish: false
xamarin:
  email: admin@mindkin.co.nz
  password:
    secure: b0qYcBpeTXhVSUl0dcpBRw==
  android: true
  ios: false
init:
#- ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
clone_script:
- ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/clone-repo-retry.ps1'))
install:
# Xamarin Packaging restore tool
- ps: $zipPath = "$($env:APPVEYOR_BUILD_FOLDER)\xpkg.zip"
- ps: (New-Object Net.WebClient).DownloadFile('https://components.xamarin.com/submit/xpkg', $zipPath)
- ps: 7z x $zipPath | Out-Null
- ps: Set-Content -path "$env:USERPROFILE\.xamarin-credentials" -value "xamarin.com,$env:XAMARIN_COOKIE"
before_build:
- xamarin-component.exe restore src\Scout.sln
build_script:
- msbuild.exe AppVeyorTest1.sln /t:Rebuild /p:Configuration=%buildconfig% /verbosity:minimal
test_script:
- ps: >-
    $env:test_assemblies.Split(';') | % {
        $assemblyName = $ExecutionContext.InvokeCommand.ExpandString($_)
        
        if ($env:test_settings){
                &vstest.console $assemblyName /InIsolation /logger:AppVeyor /settings:$env:test_settings /testcasefilter:`"TestCategory=$env:test_category`"
            } else {
                    &vstest.console $assemblyName /InIsolation /logger:AppVeyor /testcasefilter:`"TestCategory=$env:test_category`"
            }
        if ($global:LASTEXITCODE -ne 0){
            $host.SetShouldExit($global:LASTEXITCODE)
            break
        }
    }
deploy: off
